"""agrego local_id a ingresos

Revision ID: 08b36d8a2b1d
Revises: a04ee7408cb2
Create Date: 2026-04-01 19:37:40.106323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '08b36d8a2b1d'
down_revision: Union[str, Sequence[str], None] = 'a04ee7408cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('egresos_cajas', 'medio_pago',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('ingresos_lote', sa.Column('local_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingresos_lote', 'usuarios', ['local_id'], ['usuario_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingresos_lote', type_='foreignkey')
    op.drop_column('ingresos_lote', 'local_id')
    op.alter_column('egresos_cajas', 'medio_pago',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
