"""modifico unique constraint sobrantefaltante

Revision ID: 28b1a76a7a48
Revises: 0eafadd6ee31
Create Date: 2026-04-17 15:57:33.960746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28b1a76a7a48'
down_revision: Union[str, Sequence[str], None] = '0eafadd6ee31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_sf_fecha_local'), 'sobrantes_faltantes', type_='unique')
    op.create_unique_constraint('uq_sf_fecha_local', 'sobrantes_faltantes', ['fecha', 'local_id', 'usuario_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sf_fecha_local', 'sobrantes_faltantes', type_='unique')
    op.create_unique_constraint(op.f('uq_sf_fecha_local'), 'sobrantes_faltantes', ['fecha', 'local_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
