"""add ingresos_lote_chips table and fk in chips

Revision ID: 35f8dc345f79
Revises: 560d2f6cdcb5
Create Date: 2026-04-10 22:23:20.788369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35f8dc345f79'
down_revision: Union[str, Sequence[str], None] = '560d2f6cdcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos_lote_chips',
    sa.Column('ingreso_lote_chip_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.local_id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuarios.usuario_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('ingreso_lote_chip_id')
    )
    op.add_column('chips', sa.Column('ingreso_lote_chip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chips', 'ingresos_lote_chips', ['ingreso_lote_chip_id'], ['ingreso_lote_chip_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chips', type_='foreignkey')
    op.drop_column('chips', 'ingreso_lote_chip_id')
    op.drop_table('ingresos_lote_chips')
    # ### end Alembic commands ###
