"""empty message

Revision ID: 3a610fc0aaf8
Revises: 
Create Date: 2026-03-26 23:39:15.931229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a610fc0aaf8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_comisiones',
    sa.Column('config_comision_id', sa.Integer(), nullable=False),
    sa.Column('tipo_producto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_calculo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('config_comision_id'),
    sa.UniqueConstraint('tipo_producto', name='uq_config_comision_tipo')
    )
    op.create_index(op.f('ix_config_comisiones_tipo_producto'), 'config_comisiones', ['tipo_producto'], unique=False)
    op.create_table('locales',
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('local_id')
    )
    op.create_table('marcas',
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('marca_id')
    )
    op.create_table('modelos_celulares',
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('modelo_id'),
    sa.UniqueConstraint('marca', 'modelo')
    )
    op.create_table('proveedores',
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('proveedor_id')
    )
    op.create_table('tipos_accesorios',
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tipo_id')
    )
    op.create_index(op.f('ix_tipos_accesorios_nombre'), 'tipos_accesorios', ['nombre'], unique=True)
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('celulares',
    sa.Column('celular_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('imei', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.Integer(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locales.local_id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_celulares.modelo_id'], ),
    sa.ForeignKeyConstraint(['proveedor'], ['proveedores.proveedor_id'], ),
    sa.PrimaryKeyConstraint('celular_id')
    )
    op.create_index(op.f('ix_celulares_imei'), 'celulares', ['imei'], unique=True)
    op.create_table('chips',
    sa.Column('chip_id', sa.Integer(), nullable=False),
    sa.Column('compania', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_serie', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locales.local_id'], ),
    sa.PrimaryKeyConstraint('chip_id')
    )
    op.create_index(op.f('ix_chips_numero_serie'), 'chips', ['numero_serie'], unique=True)
    op.create_table('ingresos_lote',
    sa.Column('ingreso_lote_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuarios.usuario_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('ingreso_lote_id')
    )
    op.create_table('reparaciones',
    sa.Column('reparacion_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mail_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion_falla', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('costo_reparador', sa.Integer(), nullable=False),
    sa.Column('costo_final', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.local_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('reparacion_id')
    )
    op.create_table('subtipos_accesorios',
    sa.Column('subtipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_accesorios.tipo_id'], ),
    sa.PrimaryKeyConstraint('subtipo_id'),
    sa.UniqueConstraint('tipo_id', 'nombre', name='uq_tipo_nombre')
    )
    op.create_index(op.f('ix_subtipos_accesorios_nombre'), 'subtipos_accesorios', ['nombre'], unique=False)
    op.create_table('transferencias',
    sa.Column('transferencia_id', sa.Integer(), nullable=False),
    sa.Column('local_origen_id', sa.Integer(), nullable=False),
    sa.Column('local_destino_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['local_destino_id'], ['locales.local_id'], ),
    sa.ForeignKeyConstraint(['local_origen_id'], ['locales.local_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('transferencia_id')
    )
    op.create_table('ventas',
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('monto_total', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locales.local_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('venta_id')
    )
    op.create_table('accesorios',
    sa.Column('accesorio_id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('subtipo_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.marca_id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_celulares.modelo_id'], ),
    sa.ForeignKeyConstraint(['subtipo_id'], ['subtipos_accesorios.subtipo_id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_accesorios.tipo_id'], ),
    sa.PrimaryKeyConstraint('accesorio_id'),
    sa.UniqueConstraint('nombre', 'tipo_id', 'modelo_id', name='uq_accesorio_nombre_tipo_modelo')
    )
    op.create_index(op.f('ix_accesorios_sku'), 'accesorios', ['sku'], unique=True)
    op.create_table('detalles_ventas_celulares',
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('celular_id', sa.Integer(), nullable=False),
    sa.Column('imei', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio_lista', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('comision_importe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['celular_id'], ['celulares.celular_id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.venta_id'], ),
    sa.PrimaryKeyConstraint('detalle_id')
    )
    op.create_table('detalles_ventas_chips',
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('chip_id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio_lista', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('comision_importe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chip_id'], ['chips.chip_id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.venta_id'], ),
    sa.PrimaryKeyConstraint('detalle_id')
    )
    op.create_table('pagos_ventas',
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('medio_de_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('importe', sa.Integer(), nullable=False),
    sa.Column('cuotas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.venta_id'], ),
    sa.PrimaryKeyConstraint('pago_id')
    )
    op.create_table('detalles_ventas_accesorios',
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('accesorio_id', sa.Integer(), nullable=False),
    sa.Column('precio_lista', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('comision_importe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accesorio_id'], ['accesorios.accesorio_id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.venta_id'], ),
    sa.PrimaryKeyConstraint('detalle_id')
    )
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accesorio_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('ENTRADA', 'SALIDA', 'AJUSTE', 'VENTA', name='tipomovimiento'), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('ingreso_lote_id', sa.Integer(), nullable=True),
    sa.Column('transferencia_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accesorio_id'], ['accesorios.accesorio_id'], ),
    sa.ForeignKeyConstraint(['ingreso_lote_id'], ['ingresos_lote.ingreso_lote_id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.local_id'], ),
    sa.ForeignKeyConstraint(['transferencia_id'], ['transferencias.transferencia_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.venta_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_stock_accesorio_id'), 'movimientos_stock', ['accesorio_id'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_local_id'), 'movimientos_stock', ['local_id'], unique=False)
    op.create_table('stock_accesorios',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('accesorio_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.CheckConstraint('cantidad >= 0', name='ck_stock_accesorios_cantidad_no_negativa'),
    sa.ForeignKeyConstraint(['accesorio_id'], ['accesorios.accesorio_id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.local_id'], ),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('accesorio_id', 'local_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_accesorios')
    op.drop_index(op.f('ix_movimientos_stock_local_id'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_accesorio_id'), table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_table('detalles_ventas_accesorios')
    op.drop_table('pagos_ventas')
    op.drop_table('detalles_ventas_chips')
    op.drop_table('detalles_ventas_celulares')
    op.drop_index(op.f('ix_accesorios_sku'), table_name='accesorios')
    op.drop_table('accesorios')
    op.drop_table('ventas')
    op.drop_table('transferencias')
    op.drop_index(op.f('ix_subtipos_accesorios_nombre'), table_name='subtipos_accesorios')
    op.drop_table('subtipos_accesorios')
    op.drop_table('reparaciones')
    op.drop_table('ingresos_lote')
    op.drop_index(op.f('ix_chips_numero_serie'), table_name='chips')
    op.drop_table('chips')
    op.drop_index(op.f('ix_celulares_imei'), table_name='celulares')
    op.drop_table('celulares')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_accesorios_nombre'), table_name='tipos_accesorios')
    op.drop_table('tipos_accesorios')
    op.drop_table('proveedores')
    op.drop_table('modelos_celulares')
    op.drop_table('marcas')
    op.drop_table('locales')
    op.drop_index(op.f('ix_config_comisiones_tipo_producto'), table_name='config_comisiones')
    op.drop_table('config_comisiones')
    # ### end Alembic commands ###
