"""add tabla imagenes_accesorios

Revision ID: 491fc80b1b61
Revises: f5c6f1b7c577
Create Date: 2026-07-03 00:03:27.730771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '491fc80b1b61'
down_revision: Union[str, Sequence[str], None] = 'f5c6f1b7c577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagenes_accesorios',
    sa.Column('imagen_accesorio_id', sa.Integer(), nullable=False),
    sa.Column('accesorio_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['accesorio_id'], ['accesorios.accesorio_id'], ),
    sa.PrimaryKeyConstraint('imagen_accesorio_id'),
    sa.UniqueConstraint('accesorio_id', 'url', name='uq_imagen_accesorio_url')
    )
    op.create_index(op.f('ix_imagenes_accesorios_accesorio_id'), 'imagenes_accesorios', ['accesorio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imagenes_accesorios_accesorio_id'), table_name='imagenes_accesorios')
    op.drop_table('imagenes_accesorios')
    # ### end Alembic commands ###
