"""add imagen a tipos y subtipos accesorios

Revision ID: 4e787c818807
Revises: 491fc80b1b61
Create Date: 2026-07-06 21:41:08.254159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e787c818807'
down_revision: Union[str, Sequence[str], None] = '491fc80b1b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtipos_accesorios', sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subtipos_accesorios', sa.Column('imagen_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tipos_accesorios', sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tipos_accesorios', sa.Column('imagen_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_accesorios', 'imagen_public_id')
    op.drop_column('tipos_accesorios', 'imagen_url')
    op.drop_column('subtipos_accesorios', 'imagen_public_id')
    op.drop_column('subtipos_accesorios', 'imagen_url')
    # ### end Alembic commands ###
