"""unique constraint accesorios por nombre

Revision ID: 4fe609419e02
Revises: fca0823b81fe
Create Date: 2026-06-11 17:51:14.993950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4fe609419e02'
down_revision: Union[str, Sequence[str], None] = 'fca0823b81fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_accesorio_nombre_tipo_marca_celular'), 'accesorios', type_='unique')
    op.create_unique_constraint('uq_accesorio_nombre', 'accesorios', ['nombre'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_accesorio_nombre', 'accesorios', type_='unique')
    op.create_unique_constraint(op.f('uq_accesorio_nombre_tipo_marca_celular'), 'accesorios', ['nombre', 'tipo_id', 'marca_celular_id', 'modelo_celular_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
