"""add gastos table

Revision ID: 51ed49e6961f
Revises: 54e1a53e42c3
Create Date: 2026-08-04 12:52:37.922766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51ed49e6961f'
down_revision: Union[str, Sequence[str], None] = '54e1a53e42c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('REAL', 'FACTURA', name='tipogasto'), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_factura', sa.Enum('A', 'C', name='tipofactura'), nullable=True),
    sa.Column('comprada', sa.Boolean(), nullable=False),
    sa.Column('porcentaje_real', sa.Integer(), nullable=True),
    sa.Column('neto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('aporte_real', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('aporte_blanco', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('aporte_iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos')
    sa.Enum(name='tipofactura').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='tipogasto').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
