"""agregar dni_cliente a reparaciones

Revision ID: 66ac1e425bba
Revises: a27884fac502
Create Date: 2026-04-06 20:18:55.302281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66ac1e425bba'
down_revision: Union[str, Sequence[str], None] = 'a27884fac502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reparaciones', sa.Column('dni_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reparaciones', 'dni_cliente')
    # ### end Alembic commands ###
