"""add total_productos to pedidos_online

Revision ID: 7a7b7280f3cd
Revises: 7d2d14d53be9
Create Date: 2026-04-03 18:42:39.095862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a7b7280f3cd'
down_revision: Union[str, Sequence[str], None] = '7d2d14d53be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos_online', sa.Column('total_productos', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos_online', 'total_productos')
    # ### end Alembic commands ###
