"""add costo_envio to pedidos_online

Revision ID: 7d2d14d53be9
Revises: a551fd148522
Create Date: 2026-04-03 18:41:02.348964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d2d14d53be9'
down_revision: Union[str, Sequence[str], None] = 'a551fd148522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos_online', sa.Column('costo_envio', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos_online', 'costo_envio')
    # ### end Alembic commands ###
