"""cambios a la tabla reparaciones

Revision ID: 899615084f57
Revises: b4c5d6e7f8a9
Create Date: 2026-04-06 19:52:59.092116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '899615084f57'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reparaciones', sa.Column('celular', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('reparaciones', sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('reparaciones', sa.Column('total', sa.Integer(), nullable=False))
    op.add_column('reparaciones', sa.Column('adelanto', sa.Integer(), nullable=False))
    op.add_column('reparaciones', sa.Column('pago_reparador', sa.Integer(), nullable=False))
    op.drop_column('reparaciones', 'costo_final')
    op.drop_column('reparaciones', 'costo_reparador')
    op.drop_column('reparaciones', 'descripcion_falla')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reparaciones', sa.Column('descripcion_falla', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reparaciones', sa.Column('costo_reparador', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reparaciones', sa.Column('costo_final', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('reparaciones', 'pago_reparador')
    op.drop_column('reparaciones', 'adelanto')
    op.drop_column('reparaciones', 'total')
    op.drop_column('reparaciones', 'descripcion')
    op.drop_column('reparaciones', 'celular')
    # ### end Alembic commands ###
