"""fix unique constraint modelos_celulares nombre

Revision ID: 8e924056f58f
Revises: 2ee33941fe34
Create Date: 2026-04-13 22:18:40.858878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e924056f58f'
down_revision: Union[str, Sequence[str], None] = '2ee33941fe34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelos_celulares_nombre'), table_name='modelos_celulares')
    op.create_index(op.f('ix_modelos_celulares_nombre'), 'modelos_celulares', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelos_celulares_nombre'), table_name='modelos_celulares')
    op.create_index(op.f('ix_modelos_celulares_nombre'), 'modelos_celulares', ['nombre'], unique=True)
    # ### end Alembic commands ###
