"""cambios a la tabla reparaciones

Revision ID: a27884fac502
Revises: 899615084f57
Create Date: 2026-04-06 20:06:37.947055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a27884fac502'
down_revision: Union[str, Sequence[str], None] = '899615084f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reparaciones', 'pago_reparador',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reparaciones', 'pago_reparador',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
