"""add pedidos_online

Revision ID: a551fd148522
Revises: c804dd46d4e8
Create Date: 2026-04-03 17:55:53.212618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a551fd148522'
down_revision: Union[str, Sequence[str], None] = 'c804dd46d4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Agregar valor RESERVA al enum tipomovimiento (no lo detecta autogenerate)
    op.execute("ALTER TYPE tipomovimiento ADD VALUE IF NOT EXISTS 'RESERVA'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_online',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modo_entrega', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_retiro_id', sa.Integer(), nullable=True),
    sa.Column('local_stock_id', sa.Integer(), nullable=True),
    sa.Column('direccion_envio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('nombre_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mail_cliente', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('notas_cliente', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('medio_de_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referencia_pago', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('estado_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monto_total', sa.Integer(), nullable=False),
    sa.Column('notas_admin', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id_admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['local_retiro_id'], ['locales.local_id'], ),
    sa.ForeignKeyConstraint(['local_stock_id'], ['locales.local_id'], ),
    sa.ForeignKeyConstraint(['usuario_id_admin'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('pedido_id')
    )
    op.create_table('detalles_pedidos_chips',
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('chip_id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['chip_id'], ['chips.chip_id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_online.pedido_id'], ),
    sa.PrimaryKeyConstraint('detalle_id')
    )
    op.create_table('detalles_pedidos_accesorios',
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('accesorio_id', sa.Integer(), nullable=False),
    sa.Column('precio_lista', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accesorio_id'], ['accesorios.accesorio_id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_online.pedido_id'], ),
    sa.PrimaryKeyConstraint('detalle_id')
    )
    op.create_table('detalles_pedidos_celulares',
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('celular_id', sa.Integer(), nullable=False),
    sa.Column('imei', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['celular_id'], ['celulares.celular_id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_online.pedido_id'], ),
    sa.PrimaryKeyConstraint('detalle_id')
    )
    op.add_column('movimientos_stock', sa.Column('pedido_online_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movimientos_stock', 'pedidos_online', ['pedido_online_id'], ['pedido_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimientos_stock', type_='foreignkey')
    op.drop_column('movimientos_stock', 'pedido_online_id')
    op.drop_table('detalles_pedidos_celulares')
    op.drop_table('detalles_pedidos_accesorios')
    op.drop_table('detalles_pedidos_chips')
    op.drop_table('pedidos_online')
    # ### end Alembic commands ###
