"""empty message

Revision ID: c32023f96e3c
Revises: e054ac7429fd
Create Date: 2026-03-28 22:17:47.713028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c32023f96e3c'
down_revision: Union[str, Sequence[str], None] = 'e054ac7429fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modelos_celulares', sa.Column('marca_celular_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_modelo_por_marca', 'modelos_celulares', ['marca_celular_id', 'nombre'])
    op.create_foreign_key(None, 'modelos_celulares', 'marcas_celulares', ['marca_celular_id'], ['marca_celular_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modelos_celulares', type_='foreignkey')
    op.drop_constraint('uq_modelo_por_marca', 'modelos_celulares', type_='unique')
    op.drop_column('modelos_celulares', 'marca_celular_id')
    # ### end Alembic commands ###
