"""empty message

Revision ID: c804dd46d4e8
Revises: 08b36d8a2b1d
Create Date: 2026-04-01 20:08:40.399790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c804dd46d4e8'
down_revision: Union[str, Sequence[str], None] = '08b36d8a2b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ingresos_lote_local_id_fkey'), 'ingresos_lote', type_='foreignkey')
    op.create_foreign_key(None, 'ingresos_lote', 'locales', ['local_id'], ['local_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingresos_lote', type_='foreignkey')
    op.create_foreign_key(op.f('ingresos_lote_local_id_fkey'), 'ingresos_lote', 'usuarios', ['local_id'], ['usuario_id'])
    # ### end Alembic commands ###
