"""empty message

Revision ID: ccf043d7c6aa
Revises: 4fe609419e02
Create Date: 2026-06-11 22:17:35.351547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ccf043d7c6aa'
down_revision: Union[str, Sequence[str], None] = '4fe609419e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimientos_stock', sa.Column('stock_anterior', sa.Integer(), nullable=True))
    op.add_column('movimientos_stock', sa.Column('stock_nuevo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimientos_stock', 'stock_nuevo')
    op.drop_column('movimientos_stock', 'stock_anterior')
    # ### end Alembic commands ###
