"""empty message

Revision ID: e054ac7429fd
Revises: 423a55c5b492
Create Date: 2026-03-28 21:48:09.704634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e054ac7429fd'
down_revision: Union[str, Sequence[str], None] = '423a55c5b492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_accesorio_nombre_tipo_marca_celular'), 'accesorios', type_='unique')
    op.create_unique_constraint('uq_accesorio_nombre_tipo_marca_celular', 'accesorios', ['nombre', 'tipo_id', 'marca_celular_id', 'modelo_celular_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_accesorio_nombre_tipo_marca_celular', 'accesorios', type_='unique')
    op.create_unique_constraint(op.f('uq_accesorio_nombre_tipo_marca_celular'), 'accesorios', ['nombre', 'tipo_id', 'marca_celular_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
