"""add observacion to ventas

Revision ID: f5c6f1b7c577
Revises: ddce62d9648d
Create Date: 2026-06-22 00:16:44.442159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5c6f1b7c577'
down_revision: Union[str, Sequence[str], None] = 'ddce62d9648d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('observacion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'observacion')
    # ### end Alembic commands ###
