"""borre la tabla de movimientos a mano en local y la creo de nuevo, fijarse como hacer en produccion

Revision ID: fb169b6c3eee
Revises: c9d39a209c2f
Create Date: 2026-04-07 14:00:23.589768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb169b6c3eee'
down_revision: Union[str, Sequence[str], None] = 'c9d39a209c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movimientos_reparaciones_reparacion_id', table_name='movimientos_reparaciones', if_exists=True)
    op.drop_table('movimientos_reparaciones', if_exists=True)
    op.create_table('movimientos_reparaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reparacion_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado_anterior', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado_nuevo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('monto_total_anterior', sa.Integer(), nullable=True),
    sa.Column('monto_total_nuevo', sa.Integer(), nullable=True),
    sa.Column('monto_entrega_recibido', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['reparacion_id'], ['reparaciones.reparacion_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_reparaciones_reparacion_id'), 'movimientos_reparaciones', ['reparacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_reparaciones_reparacion_id'), table_name='movimientos_reparaciones')
    op.drop_table('movimientos_reparaciones')
    # ### end Alembic commands ###
