"""add pagado to reparaciones

Revision ID: fca0823b81fe
Revises: 28b1a76a7a48
Create Date: 2026-04-28 22:57:48.360151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fca0823b81fe'
down_revision: Union[str, Sequence[str], None] = '28b1a76a7a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reparaciones', sa.Column('pagado', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reparaciones', 'pagado')
    # ### end Alembic commands ###
